name: Create Flutter Project

on:
  workflow_dispatch:

jobs:
  create-flutter-project:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
      
      - name: Create Flutter project
        run: |
          flutter create my_flutter_app
          echo "✅ Flutter проект создан в папке my_flutter_app/"
      
      - name: Commit and push back to repo
        env:
          MY_GITHUB_TOKEN: ${{ secrets.MY_TOKEN}}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          git remote set-url origin https://anvistanb17-afk:${MY_GITHUB_TOKEN}@github.com/anvistanb17-afk/It-s_one_name_on_git_clock_or_github.git
          
          git add my_flutter_app/
          git commit -m "Add Flutter project" || echo "Nothing to commit"
          git push origin main
