name: test_notifier
version: 1.0.0
description: A simple package to send test notifications
repository: https://github.com/anvistanb17-afk/test_notifier

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter_local_notifications: ^17.2.2

dev_dependencies:
  test: ^1.24.0
  lints: ^3.0.0
